### ISSUE TITLE
Preview input/output

### ISSUE THREAD

**Issue by DutchNeurals** [Rusketh/FML_RatioSplitters#3]
When building a 3-splitter, the preview shows 1 input fields and 3 output fields, while those numbers have to be the other way around.
![image](https://user-images.githubusercontent.com/25212417/92990393-73bd7500-f4dc-11ea-8f00-49c0609a10d4.png)

**Comment by DutchNeurals** [comment]
Actually... After testing for 2 seconds longer..
They ARE 3 inputs.
![image](https://user-images.githubusercontent.com/25212417/92990417-bbdc9780-f4dc-11ea-9d46-d43728a90245.png)

I can place 3 input conveyor belts and only 1 output belt.

**Comment by Rusketh** [comment]
There are plenty of alternative mods to this by now. This was a first time mod and has since been deleted to allow the more functional and maintained logistics mods. This mod will no longer be updated and is no longer available on the launcher.

**Comment by DutchNeurals** [comment]
Well, I actually got on this mod by:
- Opening the Satisfactory mod manager
- Downloading/opening the "ratio splitters" mod
- Clicking on the "view on fiscit.app" link
- From there opening the Github lab link.

Did I open a wrong link somewhere?
Anyway, I am talking about the "ratio splitters" mod 0.0.3. Updated on 24-4-2020 and can be found with the "compatible" filter on.
